improved user experience

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -46,6 +46,13 @@ runs:
           aws ecr get-login-password --region "${AWS_REGION}" | docker login --username AWS --password-stdin ${{inputs.ecr_uri}}
         # Only include the GITHUB_SSH_KEY if it exists
         [ -n "${{inputs.github_ssh_key}}" ] && ARG_GITHUB_SSH_KEY='--build-arg "GITHUB_SSH_KEY=${{inputs.github_ssh_key}}"'
+
+        # ensure the dockerfile exists and is readable
+        if [ -n "${{ inputs.dockerfile }}" ] && [ ! -r "${{ inputs.dockerfile }}" ]; then
+          echo '::error::`${{ inputs.dockerfile }} was not found. Conatiner cannot be built.'
+          exit 2
+        fi
+
         # Only include the GITHUB_SHA if it is used (supresses a warning)
         grep --quiet "GITHUB_SHA" "./${{ inputs.dockerfile }}" && ARG_GITHUB_SHA='--build-arg "GITHUB_SHA=${{github.sha}}"'
         if [ -n "${{ inputs.dockerfile }}" ] && [ "${{ inputs.dockerfile }}" != "Dockerfile" ]; then
