attach the policy

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -212,7 +212,19 @@ runs:
           fi
 
           policy=$(cat ./ecr-policy.json)
-          policy_set=$(aws ecr set-repository-policy --repository-name "$ECR_REPOSITORY" --policy-text "$policy")
+          log3=/tmp/policy-error.log
+          policy_set=$(aws ecr set-repository-policy --repository-name "$ECR_REPOSITORY" --policy-text "$policy" 2>$log3)
+
+          if [ -f $log3 ]; then
+            cat $log3
+          fi
+
+          if [] -z "$policy_set" ]; then
+            echo "Could not set ECR policy for $ECR_REPOSITORY"
+            echo "Please re-register this repository to get updated credentials:"
+            echo "    glgroup ecr register-github-repo -r ${{ github.event.repository.name }} -b ${{ github.event.repository.default_branch }}"
+            exit 1
+          fi
         fi
         set -e
 
