capture docker run output

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -73,7 +73,12 @@ runs:
             -p ${{inputs.port}}:${{inputs.port}} \
             -e "HEALTHCHECK=${{inputs.healthcheck}}" \
             -e "PORT=${{inputs.port}}" \
-            --name test-container $CONTAINER_IMAGE_SHA
+            --name test-container $CONTAINER_IMAGE_SHA 2>&1 > test-container-output || {
+              code=$?
+              echo "::error::Container failed to `docker run` with exit code $code"
+              cat test-container-output
+              echo 3
+              }
 
           ATTEMPT_COUNT=0
           MAX_ATTEMPTS=5
